config/routes.rb
Rails.application.routes.draw do
  get 'bookings/index'

  get 'bookings/show'

  get 'lockers/index'

  get 'lockers/show'

  devise_for :users
  resources :majors
  resources :lockers
  resources :bookings
  root to: 'majors#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/major.rb
class Major < ApplicationRecord
  has_many :sections
  has_many :users
  has_many :bookings
end

app/controllers/majors_controller.rb
class MajorsController < ApplicationController
  before_action :set_major, only: [:show, :edit, :update, :destroy]

  # GET /majors
  # GET /majors.json
  def index
    @majors = Major.all
    @bookings = Booking.all
    @users = User.all
  end

  # GET /majors/1
  # GET /majors/1.json
  def show
    @booking = Booking.new
  end

  # GET /majors/new
  def new
    @major = Major.new
  end

  # GET /majors/1/edit
  def edit
  end

  # POST /majors
  # POST /majors.json
  def create
    @major = Major.new(major_params)

    respond_to do |format|
      if @major.save
        format.html { redirect_to @major, notice: 'Major was successfully created.' }
        format.json { render :show, status: :created, location: @major }
      else
        format.html { render :new }
        format.json { render json: @major.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /majors/1
  # PATCH/PUT /majors/1.json
  def update
    respond_to do |format|
      if @major.update(major_params)
        format.html { redirect_to @major, notice: 'Major was successfully updated.' }
        format.json { render :show, status: :ok, location: @major }
      else
        format.html { render :edit }
        format.json { render json: @major.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /majors/1
  # DELETE /majors/1.json
  def destroy
    @major.destroy
    respond_to do |format|
      format.html { redirect_to majors_url, notice: 'Major was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_major
      @major = Major.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def major_params
      params.require(:major).permit(:name, :notice, :book_start, :book_end)
    end
end

app/helpers/majors_helper.rb
module MajorsHelper
end

app/views/majors/_booking_form.html.erb
<%= form_for @booking, remote: true do |f| %>
    <%= f.hidden_field :locker_id, :value => lo.id %>
    <%= f.submit lo.loc_name %>
<% end %>

app/views/majors/_form.html.erb
<%= form_for(major) do |f| %>
  <% if major.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(major.errors.count, "error") %> prohibited this major from being saved:</h2>

      <ul>
      <% major.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :notice %>
    <%= f.text_area :notice %>
  </div>

  <div class="field">
    <%= f.label :book_start %>
    <%= f.datetime_select :book_start %>
  </div>

  <div class="field">
    <%= f.label :book_end %>
    <%= f.datetime_select :book_end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/majors/edit.html.erb
<h1>Editing Major</h1>

<%= render 'form', major: @major %>

<%= link_to 'Show', @major %> |
<%= link_to 'Back', majors_path %>

app/views/majors/index.html.erb
<% if user_signed_in? %>
    <p style="float:right"><%= current_user.email %> 님 환영합니다.</p>
    <%= link_to '로그아웃', destroy_user_session_path, method: :delete, data: {confirm: "정말 로그아웃 하시겠습니까?"}%>
<% else %>
    <%= link_to '로그인', new_user_session_path %>
    <%= link_to '회원가입', new_user_registration_path  %>
<% end %>


<p id="notice"><%= notice %></p>

<h1>Majors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Notice</th>
      <th>Book start</th>
      <th>Book end</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @majors.each do |major| %>
      <tr>
        <td><%= major.name %></td>
        <td><%= major.notice %></td>
        <td><%= major.book_start %></td>
        <td><%= major.book_end %></td>
        <td><%= link_to 'Show', major_url(major) %></td>
        <td><%= link_to 'Edit', edit_major_path(major) %></td>
        <td><%= link_to 'Destroy', major, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Major', new_major_path %>

<% @bookings.each do |b| %>
    <p><%= b.created_at%> // <%= b.user.email %>님께서 <%= b.major.name %>의 사물함 <%= b.locker.loc_name %>을 예약하셨습니다. <%= link_to '삭제', b, method: :delete, data: { confirm: '정말 삭제하시겠습니까?'} %></p>
<% end %>
<hr>

<% @users.each do |u| %>
  <p><%= u.email %> // <%= u.major.name %> // <% unless u.booking.nil? %> <%= u.booking.locker.loc_name %> <% else %> 미예약 <% end %></p>
<% end %>

app/views/majors/new.html.erb
<h1>New Major</h1>

<%= render 'form', major: @major %>

<%= link_to 'Back', majors_path %>

app/views/majors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @major.name %>
</p>

<p>
  <strong>Notice:</strong>
  <%= @major.notice %>
</p>

<p>
  <strong>Book start:</strong>
  <%= @major.book_start %>
</p>

<p>
  <strong>Book end:</strong>
  <%= @major.book_end %>
</p>

  <% @major.sections.each do |sec| %>
    <%= sec.name %> // <%= sec.location %>

    <table>
      <% (sec.len_y).times do |y| %>
      <tr>
        <% (sec.len_x).times do |x| %>
            <% @loc = (sec.lockers.where(loc_x: x+1, loc_y: y+1))[0] %>
            <% unless @loc.booking.nil? %>
              <td style="color: red"><%= @loc.loc_name %></td>
            <% else %>
                <td>
                  <%= render 'booking_form', lo: @loc %>
                </td>
            <% end %>
        <% end %>
      </tr>
      <% end %>
    </table>

  <% end %>




<%= link_to 'Edit', edit_major_path(@major) %> |
<%= link_to 'Back', majors_path %>